baseurl = "https://calvin.io/"
languageCode = "en-us"
title = "Calvin Leung Huang"
theme = "hugo-cactus-theme"
canonifyurls = true
googleAnalytics = "UA-79255777-1"

[params]
  name = "Calvin Leung Huang"
  description = ""
  bio = "Software Engineer - HashiCorp - Boston"
  enableRSS = false

  title404 = "Uh Oh!"
  subtitle404 = "I couldn't find what you're looking for."

  iconFont = "mono-social"
  socialIconStyle = "circle"

[social]
  twitter  = "https://www.twitter.com/cleung2010"
  githubalt   = "https://www.github.com/calvn"
  linkedin = "https://www.linkedin.com/in/calvinleunghuang"
